helm:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 37.2.0                # pick your tested version
  releaseName: traefik
  namespace: kube-system
  valuesFiles:
    - values.yaml
