apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
stringData:
  # Replace this with your bcrypt hash (do NOT put plaintext here).
  # Generate one with:  argocd account bcrypt --password 'YourStrongPass'
  # or:                 htpasswd -bnBC 10 "" 'YourStrongPass' | tr -d ':\n'
  admin.password: "$2y$10$GaxrY4Lovzc.RbjXKDE5keRgrjtWmyfveF8WzAjhhAHZLQ.4QnbUq"

  # Can be any past/fixed timestamp; bump when rotating the password.
  # (Tokens issued before this time are invalidated.)
  admin.passwordMtime: "2025-11-02T00:00:00Z"
