# platform-baseline/argocd-kustomize/patches/argocd-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Replace with your bcrypt hash:
  admin.password: "$2y$10$GaxrY4Lovzc.RbjXKDE5keRgrjtWmyfveF8WzAjhhAHZLQ.4QnbUq"
  # Update this anytime you change the password (RFC3339)
  admin.passwordMtime: "2025-11-02T09:00:00Z"
